version: "3.8"
services:
  flaskapp:
    build: .
    container_name: flask-employee-app
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./data:/app   # persist db & code (agar db update hota h to safe rahe)
