name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Flask App on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2HOST }}
          username: ubuntu
          key: ${{ secrets.EC2KEY }}
          script: |
            cd /var/www/html/flask-employee-app
            # Ensure repo is safe & owned by ubuntu
            sudo chown -R ubuntu:ubuntu /var/www/html/flask-employee-app
            git config --global --add safe.directory /var/www/html/flask-employee-app
            git reset --hard
            git pull origin main
            docker compose down
            docker rm -f flask-employee-app || true
            docker compose build --no-cache
            docker compose up -d --force-recreate --remove-orphans
